[package]
name = "hidapi"
version = "0.1.0"
authors = ["Jonas Malaco <jonas@protocubo.io>"]
edition = "2018"

[dependencies]
hidapi = { version = "1.2", default-features = false, features = ["linux-static-hidraw"] }
