[package]
name = "hello_server2"
version = "0.1.0"
authors = ["Jonas Malaco <jonas@protocubo.io>"]
edition = "2018"

[dependencies]
signal-hook = "0.1"
uuid = { version = "0.8", features = ["v4"] }

[profile.release]
lto = "thin"
debug = true
