[target.arm-unknown-linux-musleabihf]
linker = "../../../raspberrypi-tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-gnueabihf]
linker = "../../../raspberrypi-tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"
